package fr.houseofcode.dap.ws;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
/**
 * Check course for standard user.
 * @author djer1
 */
public class CourseexistsTest extends SeleniumBaseClasse {

    @Test
    public void courseexists() {
        SeleniumDapHelper.login(getDriver());

        getDriver().findElement(By.xpath("//span[contains(.,'Tests et Recette')]")).click();
        assertThat(getDriver().findElement(By.cssSelector("#section-1 .sectionname a")).getText(), is("La qualité"));
    }
}
