package fr.houseofcode.dap.ws.web;

// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;

/**
 * Check courses for standart user.
 * @author house
 *
 */
public class CourseexistsTest extends SeleniumBaseClass {

    /**
     * Check courses.
     */
    @Test
    public void courseexists() {
        SeleniumDapHelper.login(super.getDriver());
        // Test name: Course exists
        super.getDriver().get("http://djer13-moodle.clicketcloud.com/my/");
        super.getDriver().manage().window().setSize(new Dimension(915, 629));
        super.getDriver().findElement(By.xpath("//span[contains(.,'Tests et Recette')]")).click();
    }
}
